### ISSUE TITLE
DSCSModLoaderImpl::readWorkTables Wrong

### ISSUE THREAD

**Issue by zyl9241** [SydMontague/DSCSModLoader#34]
Hello, I have found an issue in your code:
In the method of ”DSCSModLoaderImpl::readWorkTables“ and "DSCSModLoaderImpl::readFlagTables",  ”itr++“    is missing:

void DSCSModLoaderImpl::readWorkTables(std::vector<uint8_t> data)
{
    std::size_t entryCount = data.size() / sizeof(WorkTable);
    WorkTable* itr         = reinterpret_cast<WorkTable*>(data.data());

    workTables.clear();

    for (int32_t i = 0; i < entryCount; i++) {
        workTables.insert(std::make_pair(std::string(itr->getName()), *itr));
        itr++;        <===Here
    }
}

void DSCSModLoaderImpl::readFlagTables(std::vector<uint8_t> data)
{
    std::size_t entryCount = data.size() / sizeof(FlagTable);
    FlagTable* itr         = reinterpret_cast<FlagTable*>(data.data());

    flagTables.clear();

    for (int32_t i = 0; i < entryCount; i++) {
        flagTables.insert(std::make_pair(std::string(itr->getName()), *itr));
        itr++;       <===Here
    }
}

**Comment by SydMontague** [comment]
Thanks, should be fixed in the code now. :+1:
