### ISSUE TITLE
[C++ API] Custom MVGL loaders

### ISSUE THREAD

**Issue by Pherakki** [SydMontague/DSCSModLoader#5]
Loading additional AFS2 archives may already exist, as implied by the bgm.csv etc., but I have not tested whether this is the case.
and dangerous to put in the hands of mod authors (in the sense that they're probably going to overwrite data they really shouldn't), but programs like the mod manager might be able to use this to load more than 16GiB of custom data.

**Comment by Pherakki** [comment]
AFS2 was sorted in another issue.
Regarding MDB1 archives - maybe the ModLoader could be provided with a Manifest that tells it which MVGLs to load? There's probably a smarter idea, but a manifest file could work..?

**Comment by SydMontague** [comment]
Added via config in v0.1.0-alpha
