### ISSUE TITLE
[C++ API] Expose flag table?

### ISSUE THREAD

**Issue by Pherakki** [SydMontague/DSCSModLoader#7]
The Squirrel scripts make extensive use of flags to set the game state, and use getters and setters for these flags. Some function to get the value of all flags might be useful for, e.g., debugging.

**Comment by Pherakki** [comment]
Addendum: Re-implement this.Flag.Set

**Comment by SydMontague** [comment]
Implemented in
`dscs::getGameContext()->flags`
